import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { loadExternalSources, outputs } from '../../scripts/load-external-sources.js';

describe('load-external-sources', () => {
  let dataDir;

  beforeEach(() => {
    dataDir = mkdtempSync(join(tmpdir(), 'external-sources-'));
    vi.spyOn(console, 'log').mockImplementation(() => {});
    vi.spyOn(console, 'error').mockImplementation(() => {});
  });
  afterEach(() => rmSync(dataDir, { recursive: true, force: true }));

  it('targets the data files the site imports', () => {
    expect(outputs.map(({ file, exportName }) => [file, exportName])).toEqual([
      ['official-publications.js', 'officialPublications'],
      ['linkedin.js', 'linkedinPosts'],
    ]);
  });

  it('merges every source of an output, and keeps stored entries when a source fails', async () => {
    writeFileSync(
      join(dataDir, 'pubs.js'),
      `export const pubs = ${JSON.stringify([{ url: 'https://b.test/stored', date: '2025-01-01', title: 'Stored' }])};\n`,
    );

    const [result] = await loadExternalSources({
      dataDir,
      outputs: [
        {
          file: 'pubs.js',
          exportName: 'pubs',
          sources: [
            { label: 'A', fetch: async () => [{ url: 'https://a.test/1', date: '2026-01-01', title: 'From A' }] },
            { label: 'B', fetch: async () => Promise.reject(new Error('boom')) },
          ],
        },
      ],
    });

    expect(result).toEqual({ file: 'pubs.js', total: 2, added: 1, updated: 0, kept: 1 });
    const written = readFileSync(join(dataDir, 'pubs.js'), 'utf-8');
    expect(written).toMatch(/^\/\/ Generated by `npm run load-external-sources`/);
    expect(written).toContain('From A');
    expect(written).toContain('Stored');
    expect(console.error).toHaveBeenCalledWith('[load-external-sources] B failed: boom');
  });
});
